apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: python-app-ingressroute
  namespace: python-app
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`python-app.local`)
    kind: Rule
    services:
    - name: python-app
      port: 80